// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbSg4GBQ_IRXPLc2yKNNpHKi4pVjdQa4k',
    appId: '1:1067217434942:web:5d198580aa067683e5546f',
    messagingSenderId: '1067217434942',
    projectId: 'kine-8c247',
    authDomain: 'kine-8c247.firebaseapp.com',
    storageBucket: 'kine-8c247.firebasestorage.app',
    measurementId: 'G-DXEG8CR66F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpPJuANliHY_VAA-GCNXDc1TnIBX7hGa8',
    appId: '1:1067217434942:android:9f568f0d211ce7e7e5546f',
    messagingSenderId: '1067217434942',
    projectId: 'kine-8c247',
    storageBucket: 'kine-8c247.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMNDn-bAwsiiN_eH5V5nsEKaV3Z37fbwU',
    appId: '1:1067217434942:ios:005220ab0aa0d4eae5546f',
    messagingSenderId: '1067217434942',
    projectId: 'kine-8c247',
    storageBucket: 'kine-8c247.firebasestorage.app',
    iosBundleId: 'com.example.kineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMNDn-bAwsiiN_eH5V5nsEKaV3Z37fbwU',
    appId: '1:1067217434942:ios:005220ab0aa0d4eae5546f',
    messagingSenderId: '1067217434942',
    projectId: 'kine-8c247',
    storageBucket: 'kine-8c247.firebasestorage.app',
    iosBundleId: 'com.example.kineApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbSg4GBQ_IRXPLc2yKNNpHKi4pVjdQa4k',
    appId: '1:1067217434942:web:419059c11e80024be5546f',
    messagingSenderId: '1067217434942',
    projectId: 'kine-8c247',
    authDomain: 'kine-8c247.firebaseapp.com',
    storageBucket: 'kine-8c247.firebasestorage.app',
    measurementId: 'G-QX0BN91F5N',
  );
}
